name: Create build artifact

inputs:
  build-command:
    required: false
    default: npm run build

  keep-files:
    required: false
    default: .

  exclude-files:
    required: false
    default: .git

runs:
  using: node12
  main: dist/index.js
