name: Create build artifact

inputs:
  build-command:
    required: false
    default: npm run build

  include:
    required: false
    default: .

  exclude:
    required: false
    default: .git

runs:
  using: node12
  main: dist/index.js
